//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBarDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantEvent
    {
        public int RestaurantEventID { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public System.DateTime EventEndDate { get; set; }
        public int RestaurantId { get; set; }
        public System.DateTime EventPublicationDate { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
