//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBarDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTables
    {
        public int TableId { get; set; }
        public int TableNumber { get; set; }
        public string TableBarcode { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
