//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBarDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantDetails
    {
        public int RestaurantDetailsId { get; set; }
        public int RestaurantId { get; set; }
        public string RestaurantDirectoryGuid { get; set; }
        public string RestaurantDescription { get; set; }
        public string RestaurantThumbnail { get; set; }
        public string RestaurantProgram { get; set; }
        public string RestaurantContact { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
