//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBarDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantLocations
    {
        public int LocationId { get; set; }
        public string RestaurantCounty { get; set; }
        public string RestaurantCity { get; set; }
        public string RestaurantAddress { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
