//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
namespace eBarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract] 
     public  partial class Languages
    {
        [DataMember]
    public int LanguageId { get; set; }
        [DataMember]
    public string LanguageCode { get; set; }
        [DataMember]
    public string LanguageCountry { get; set; }
        [DataMember]
    public string LanguageName { get; set; }
    }
}
