//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
namespace eBarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract] 
     public  partial class RestaurantProductsCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantProductsCategories()
        {
            this.RestaurantProducts = new HashSet<RestaurantProducts>();
        }
    
        [DataMember]
    public int CategoryId { get; set; }
        [DataMember]
    public int RestaurantId { get; set; }
        [DataMember]
    public string CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantProducts> RestaurantProducts { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
