//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
namespace eBarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract] 
     public  partial class RestaurantLocations
    {
        [DataMember]
    public int LocationId { get; set; }
        [DataMember]
    public string RestaurantCity { get; set; }
        [DataMember]
    public decimal Latitude { get; set; }
        [DataMember]
    public decimal Longitude { get; set; }
        [DataMember]
    public int RestaurantId { get; set; }
        [DataMember]
    public string RestaurantAddress { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
