//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
namespace eBarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract] 
     public  partial class UserResetPasswordCodes
    {
        [DataMember]
    public int UserResetPwdId { get; set; }
        [DataMember]
    public int UserID { get; set; }
        [DataMember]
    public string ResetCode { get; set; }
        [DataMember]
    public System.DateTime CreationDate { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
