//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResetPasswordCodes
    {
        public int UserResetPwdId { get; set; }
        public int UserID { get; set; }
        public string ResetCode { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual UserTbl UserTbl { get; set; }
    }
}
